### ISSUE TITLE
Integration Display not found

### ISSUE THREAD

**Issue by GuruPG** [daemondazz/homeassistant-displays#24]
This has seemed to stop working with the latest HA update.
Running the following version:
Home Assistant OS 5.13
Core 2021.6.1
Supervisor 2021.05.4

I have not changed anything in the YAML.
it has always been:

Copy to clipboard
display:
  - platform: fully_kiosk
    name: Bathroom Tablet
    host: '192.168.0.179'
    password: !secret http_password
since the update it will not let me reboot unless i remove the above from the YAML.
it comes back and says:

Copy to clipboard
[2743349152] The system cannot restart because the configuration is not valid: Component error: display - Integration 'display' not found.
11:50:46 – (ERROR) Home Assistant WebSocket API
The system cannot restart because the configuration is not valid: Component error: display - Integration 'display' not found.
11:50:46 – (ERROR) Home Assistant Supervisor
anyone else had any issues?

**Comment by daemondazz** [comment]
My apologies, this should be fixed in commit 80d79cc.

**Comment by GuruPG** [comment]
I have deleted my 'display' and 'fully_kiosk' folders from HA and replaced with the latest ones you have just updated but I'm having the same issue.

**Comment by Stephan1908** [comment]
Yes, i have the same error too

**Comment by daemondazz** [comment]
Are you able to check the log file for any errors or stack traces during startup? I am running on 2021.6.1 here without issue.

**Comment by Stephan1908** [comment]
This error i get, when i check config:

![grafik](https://user-images.githubusercontent.com/60405276/120900886-c37a3880-c637-11eb-8ef3-80b93cec67a3.png)

**Comment by oneseventhree** [comment]
> This error i get, when i check config:
> 
> ![grafik](https://user-images.githubusercontent.com/60405276/120900886-c37a3880-c637-11eb-8ef3-80b93cec67a3.png)

I am getting the same error after replacing the older folders with the new ones.

**Comment by adorobis** [comment]
I have just created a PR that fixes this issue.
https://github.com/daemondazz/homeassistant-displays/pull/26

**Comment by daemondazz** [comment]
Thanks adorobis. I've merged your pull request.

For those playing along at home, I've also restructured the project a little and updated the README to make installation and upgrading easier so removing and re-copying the files isn't needed any more.

**Comment by e-rockHH** [comment]
I still get this error even after a fresh git clone. I'm on 2021.7.4.
